### ISSUE TITLE
CI & radiator working

### ISSUE THREAD

**Issue by ilmoraunio** [ilmoraunio/rulebased-chat#1]
All branches of development should be automatically tested in CI to ensure that the build is never broken.

Get an easily configurable & runnable CI service working to provide an active radiator for the repository.

**Comment by ilmoraunio** [comment]
CircleCI seems to provide an easy, quick configurable setup for CI. Investigating this.

**Comment by ilmoraunio** [comment]
I'm having trouble getting cucumber tests working. They work locally with `lein cucumber`, but not in CircleCI.

Relevant stack trace:

```
Retrieving org/jsoup/jsoup/1.6.1/jsoup-1.6.1.jar from central
Retrieving bultitude/bultitude/0.1.7/bultitude-0.1.7.jar from clojars
WARNING: update already refers to: #'clojure.core/update in namespace: useful.map, being replaced by: #'useful.map/update
WARNING: update already refers to: #'clojure.core/update in namespace: leiningen.core.project, being replaced by: #'useful.map/update
Running cucumber...
Looking for features in:  [/home/ubuntu/rulebased-chat/test/features]
Looking for glue in:  [/home/ubuntu/rulebased-chat/test/features/step_definitions]
.
ERROR in clojure.lang.PersistentList$EmptyList@1 (util.clj:343)
expected: (= title (taxi/text "div.jumbotron > h1"))
..F-

2 Scenarios (1 failed, 1 passed)
5 Steps (1 failed, 1 skipped, 3 passed)
2m8.022s

org.openqa.selenium.NoSuchElementException: 
When an element cannot be found in clj-webdriver, nil is returned. You've just tried to perform an action on an element that returned as nil for the search query you used. Please verify the query used to locate this element; it is not on the current page.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'box845', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.14.28-031428-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
	at clj_webdriver.util$throw_nse.invoke(util.clj:343)
	at clj_webdriver.util$throw_nse.invoke(util.clj:341)
	at clj_webdriver.core$eval5270$fn__5275.invoke(core_element.clj:423)
	at clj_webdriver.core$eval4434$fn__4448$G__4415__4455.invoke(core.clj:116)
	at clj_webdriver.taxi$input_text.invoke(taxi.clj:1172)
	at clj_webdriver.taxi$input_text.invoke(taxi.clj:1170)
	at cucumber.runtime.clj$eval5800$fn__5801.invoke(register_user_steps.clj:10)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at cucumber.runtime.clj$add_step_definition$reify__1953.execute(clj.clj:83)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:298)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:48)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:163)
	at cucumber.runtime.Runtime.run(Runtime.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at leiningen.cucumber.util$run_cucumber_BANG_$fn__19.invoke(util.clj:31)
	at leiningen.cucumber.util$run_cucumber_BANG_.invoke(util.clj:30)
	at user$eval1902.invoke(form-init2338584227945471039.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at ✽.And I enter my user info(register_user.feature:6)


Subprocess failed lein cucumber returned exit code 1
```

**Comment by ilmoraunio** [comment]
bc05cba9e09a49e75b184da2116e9bfb2cb4fc28
d6f446b30685256dfdf5c5fc43be5e5108029019
598c416c01c3922fb20ed3504732777fe38a8fd4
ebb0c1b2b1a2bb296063399672c2cb994cf3defe
