### ISSUE TITLE
Registering a user causes an IllegalArgumentException

### ISSUE THREAD

**Issue by ilmoraunio** [ilmoraunio/rulebased-chat#5]
Entering valid username and password on the registration page causes the following stack:

```
java.lang.IllegalArgumentException: db-spec null is missing a required parameter
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:289)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:599)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at rulebased_chat.dao.users$create_user.invoke(users.clj:17)
	at rulebased_chat.routes.services$fn__21704$fn__21706$fn__21708.invoke(services.clj:105)
	at buddy.auth.accessrules$restrict$fn__17497.invoke(accessrules.clj:374)
	at compojure.response$eval200$fn__201.invoke(response.clj:33)
	at compojure.response$eval167$fn__168$G__158__175.invoke(response.clj:6)
	at compojure.core$make_route$fn__1843.invoke(core.clj:130)
	at compojure.core$wrap_route_middleware$fn__1839.invoke(core.clj:118)
	at compojure.core$if_route$fn__1811.invoke(core.clj:41)
	at compojure.core$if_method$fn__1803.invoke(core.clj:27)
	at compojure.api.meta$body_coercer_middleware$fn__11362.invoke(meta.clj:57)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1854.invoke(core.clj:149)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at rulebased_chat.routes.services$fn__21704.invoke(services.clj:96)
	at compojure.core$if_context$fn__1912.invoke(core.clj:211)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1854.invoke(core.clj:149)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at ring.swagger.middleware$wrap_swagger_data$fn__8728.invoke(middleware.clj:33)
	at ring.middleware.http_response$wrap_http_response$fn__6635.invoke(http_response.clj:8)
	at ring.swagger.middleware$wrap_validation_errors$fn__8753.invoke(middleware.clj:68)
	at compojure.api.middleware$wrap_exceptions$fn__9795.invoke(middleware.clj:55)
	at ring.swagger.middleware$wrap_swagger_data$fn__8728.invoke(middleware.clj:33)
	at compojure.api.middleware$wrap_options$fn__9802.invoke(middleware.clj:83)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_response$wrap_format_response$fn__6560.invoke(format_response.clj:175)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6671.invoke(keyword_params.clj:32)
	at ring.middleware.nested_params$wrap_nested_params$fn__6720.invoke(nested_params.clj:69)
	at ring.middleware.params$wrap_params$fn__6748.invoke(params.clj:57)
	at compojure.api.middleware$wrap_options$fn__9802.invoke(middleware.clj:83)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1854.invoke(core.clj:149)
	at clojure.lang.Var.invoke(Var.java:379)
	at ring.middleware.cors$wrap_cors$fn__19174.invoke(cors.clj:150)
	at rulebased_chat.middleware$wrap_identity$fn__19199.invoke(middleware.clj:72)
	at buddy.auth.middleware$wrap_authentication$fn__19072.invoke(middleware.clj:41)
	at ring.middleware.session_timeout$wrap_idle_session_timeout$fn__19035.invoke(session_timeout.clj:25)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_response$wrap_format_response$fn__6560.invoke(format_response.clj:175)
	at ring.middleware.flash$wrap_flash$fn__18562.invoke(flash.clj:31)
	at ring.middleware.session$wrap_session$fn__18795.invoke(session.clj:85)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6671.invoke(keyword_params.clj:32)
	at ring.middleware.nested_params$wrap_nested_params$fn__6720.invoke(nested_params.clj:69)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__18839.invoke(multipart_params.clj:106)
	at ring.middleware.params$wrap_params$fn__6748.invoke(params.clj:57)
	at ring.middleware.cookies$wrap_cookies$fn__18676.invoke(cookies.clj:171)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__18962.invoke(absolute_redirects.clj:36)
	at ring.middleware.resource$wrap_resource$fn__18894.invoke(resource.clj:24)
	at ring.middleware.content_type$wrap_content_type$fn__12281.invoke(content_type.clj:26)
	at ring.middleware.default_charset$wrap_default_charset$fn__18939.invoke(default_charset.clj:26)
	at ring.middleware.not_modified$wrap_not_modified$fn__12304.invoke(not_modified.clj:40)
	at ring.middleware.x_headers$wrap_xss_protection$fn__18540.invoke(x_headers.clj:71)
	at ring.middleware.x_headers$wrap_frame_options$fn__18528.invoke(x_headers.clj:38)
	at ring.middleware.x_headers$wrap_content_type_options$fn__18534.invoke(x_headers.clj:53)
	at ring.middleware.webjars$wrap_webjars$fn__19122.invoke(webjars.clj:34)
	at rulebased_chat.middleware$wrap_servlet_context$fn__19183.invoke(middleware.clj:34)
	at rulebased_chat.middleware$wrap_internal_error$fn__19189.invoke(middleware.clj:39)
	at immutant.web.internal.undertow$create_http_handler$reify__24029.handleRequest(undertow.clj:130)
	at org.projectodd.wunderboss.web.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:103)
	at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: db-spec null is missing a required parameter
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:289)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:599)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at rulebased_chat.dao.users$create_user.invoke(users.clj:17)
	at rulebased_chat.routes.services$fn__21704$fn__21706$fn__21708.invoke(services.clj:105)
	at buddy.auth.accessrules$restrict$fn__17497.invoke(accessrules.clj:374)
	at compojure.response$eval200$fn__201.invoke(response.clj:33)
	at compojure.response$eval167$fn__168$G__158__175.invoke(response.clj:6)
	at compojure.core$make_route$fn__1843.invoke(core.clj:130)
	at compojure.core$wrap_route_middleware$fn__1839.invoke(core.clj:118)
	at compojure.core$if_route$fn__1811.invoke(core.clj:41)
	at compojure.core$if_method$fn__1803.invoke(core.clj:27)
	at compojure.api.meta$body_coercer_middleware$fn__11362.invoke(meta.clj:57)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1854.invoke(core.clj:149)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at rulebased_chat.routes.services$fn__21704.invoke(services.clj:96)
	at compojure.core$if_context$fn__1912.invoke(core.clj:211)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1854.invoke(core.clj:149)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at ring.swagger.middleware$wrap_swagger_data$fn__8728.invoke(middleware.clj:33)
	at ring.middleware.http_response$wrap_http_response$fn__6635.invoke(http_response.clj:8)
	at ring.swagger.middleware$wrap_validation_errors$fn__8753.invoke(middleware.clj:68)
	at compojure.api.middleware$wrap_exceptions$fn__9795.invoke(middleware.clj:55)
	at ring.swagger.middleware$wrap_swagger_data$fn__8728.invoke(middleware.clj:33)
	at compojure.api.middleware$wrap_options$fn__9802.invoke(middleware.clj:83)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_response$wrap_format_response$fn__6560.invoke(format_response.clj:175)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6671.invoke(keyword_params.clj:32)
	at ring.middleware.nested_params$wrap_nested_params$fn__6720.invoke(nested_params.clj:69)
	at ring.middleware.params$wrap_params$fn__6748.invoke(params.clj:57)
	at compojure.api.middleware$wrap_options$fn__9802.invoke(middleware.clj:83)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at compojure.core$routing$fn__1850.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1854.invoke(core.clj:149)
	at clojure.lang.Var.invoke(Var.java:379)
	at ring.middleware.cors$wrap_cors$fn__19174.invoke(cors.clj:150)
	at rulebased_chat.middleware$wrap_identity$fn__19199.invoke(middleware.clj:72)
	at buddy.auth.middleware$wrap_authentication$fn__19072.invoke(middleware.clj:41)
	at ring.middleware.session_timeout$wrap_idle_session_timeout$fn__19035.invoke(session_timeout.clj:25)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_params$wrap_format_params$fn__5875.invoke(format_params.clj:113)
	at ring.middleware.format_response$wrap_format_response$fn__6560.invoke(format_response.clj:175)
	at ring.middleware.flash$wrap_flash$fn__18562.invoke(flash.clj:31)
	at ring.middleware.session$wrap_session$fn__18795.invoke(session.clj:85)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6671.invoke(keyword_params.clj:32)
	at ring.middleware.nested_params$wrap_nested_params$fn__6720.invoke(nested_params.clj:69)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__18839.invoke(multipart_params.clj:106)
	at ring.middleware.params$wrap_params$fn__6748.invoke(params.clj:57)
	at ring.middleware.cookies$wrap_cookies$fn__18676.invoke(cookies.clj:171)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__18962.invoke(absolute_redirects.clj:36)
	at ring.middleware.resource$wrap_resource$fn__18894.invoke(resource.clj:24)
	at ring.middleware.content_type$wrap_content_type$fn__12281.invoke(content_type.clj:26)
	at ring.middleware.default_charset$wrap_default_charset$fn__18939.invoke(default_charset.clj:26)
	at ring.middleware.not_modified$wrap_not_modified$fn__12304.invoke(not_modified.clj:40)
	at ring.middleware.x_headers$wrap_xss_protection$fn__18540.invoke(x_headers.clj:71)
	at ring.middleware.x_headers$wrap_frame_options$fn__18528.invoke(x_headers.clj:38)
	at ring.middleware.x_headers$wrap_content_type_options$fn__18534.invoke(x_headers.clj:53)
	at ring.middleware.webjars$wrap_webjars$fn__19122.invoke(webjars.clj:34)
	at rulebased_chat.middleware$wrap_servlet_context$fn__19183.invoke(middleware.clj:34)
	at rulebased_chat.middleware$wrap_internal_error$fn__19189.invoke(middleware.clj:39)
	at immutant.web.internal.undertow$create_http_handler$reify__24029.handleRequest(undertow.clj:130)
	at org.projectodd.wunderboss.web.async.websocket.UndertowWebsocket$2.handleRequest(UndertowWebsocket.java:103)
	at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ilmoraunio** [comment]
This is caused by db configuration missing from profiles.clj. Closing this now. Opened a ticket regarding the automation of and necessary pre-dependency configuration.
